// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF4zQMSFRQkZlOQJBydivSEsQSEbTKawQ',
    appId: '1:367862289249:android:bc5f47d64bfd35c544ab20',
    messagingSenderId: '367862289249',
    projectId: 'practiceproject-2f6c8',
    storageBucket: 'practiceproject-2f6c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl5E5kgBnL_C1nSEmeAlTC1N-w1hzACeA',
    appId: '1:367862289249:ios:30f827cedeb864b844ab20',
    messagingSenderId: '367862289249',
    projectId: 'practiceproject-2f6c8',
    storageBucket: 'practiceproject-2f6c8.appspot.com',
    iosBundleId: 'com.example.assignment3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl5E5kgBnL_C1nSEmeAlTC1N-w1hzACeA',
    appId: '1:367862289249:ios:c8ac3355f8c4c95644ab20',
    messagingSenderId: '367862289249',
    projectId: 'practiceproject-2f6c8',
    storageBucket: 'practiceproject-2f6c8.appspot.com',
    iosBundleId: 'com.example.assignment3.RunnerTests',
  );
}
